runtime: python27
api_version: 1
threadsafe: true

handlers:


- url: /js
  static_dir: js


- url: /post
  script:app10.app
  login: required
  auth_fail_action: unauthorized
  
  - url: /.*
  script: app10.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest


